### ISSUE TITLE
Refine keyboard-centric UX when adding a row filter

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#2774]
When initially clicking the "+" / add filter button, it isn't possible to start typing to find the column you want:

![image](https://github.com/posit-dev/positron/assets/329591/ebda1f4b-343d-498f-a42d-26f1cb7ae6d0)

When expanding the dropdown, the search box is not focused

![image](https://github.com/posit-dev/positron/assets/329591/996a65e3-affa-458d-83b9-f938affd112c)

After finding the column of interest, using the arrow keys to select the column does not work yet, you have to click

![image](https://github.com/posit-dev/positron/assets/329591/acf59166-5ea6-446b-aac0-cbe3446f20eb)

It would be great to set focus as appropriate and enable an efficient keyboard centric experience to be able to add and change filters quickly

**Comment by softwarenerd** [comment]
These items are fixed as of 5/2/2025.

**Comment by juliasilge** [comment]
For QA info, check out the PR #4620 from a while back. We still don't focus the search box, but the user can start typing to get the column name. I chatted with @softwarenerd and we think that we are not a fan of the idea that we should shove focus into the search box when the column selector drop down is opened.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.06.0-39
    OS Version          : OSX

### Test scenario(s) 

Original filing comments addressed except as noted by Julia in previous comment.

Link(s) to TestRail test cases run or created:
