### ISSUE TITLE
targets::tar_visnetwork() shows a blank screen only.

### ISSUE THREAD

**Issue by CorradoLanera** [posit-dev/positron#3783]
Type: <b>Bug</b>

`targets::tar_visnetwork` open in plots and not in viewer, showing a blank screen only instead of the widget

![image](https://github.com/posit-dev/positron/assets/6473683/f144cdfc-f69a-4f4c-be0e-fa11af41f831)

## reprex
```r
tar_dir({ # tar_dir() runs code from a temp dir for CRAN.
     tar_script({
       tar_option_set()
       list(
         tar_target(y1, 1 + 1),
         tar_target(y2, 1 + 1),
         tar_target(z, y1 + y2, description = "sum of two other sums")
       )
     })
     tar_visnetwork()
     tar_visnetwork(allow = starts_with("y")) # see also any_of()
})
```

VS Code version: Positron 1.90.0 (a893e5b282612ccb2200102957ac38d3c14e5196, 2024-06-26T01:33:58.809Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (16.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jthomasmock** [comment]
At a lower level, I tried this, the underlying library for `visnetwork` functions:

```r
library(visNetwork)
# minimal example
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))
visNetwork(nodes, edges, width = "100%")
```

This also shows in the Plots pane but successfully displays.

![image](https://github.com/posit-dev/positron/assets/29187501/cb81c2ab-3030-44cb-9e06-c7771061db0d)


<details><summary>Positron Info</summary>

Positron Version: 2024.06.1 (Universal) build 27
Code - OSS Version: 1.90.0
Commit: a893e5b282612ccb2200102957ac38d3c14e5196
Date: 2024-06-26T02:08:06.673Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0

</details>

**Comment by jmcphers** [comment]
See #2023; there's a known issue preventing some HTML widgets from showing up correctly in Positron. I think this is another instance of that problem.

**Comment by jmcphers** [comment]
Should be resolved with #4151:

<img width="1409" alt="image" src="https://github.com/user-attachments/assets/43bb292e-50c0-46b6-a4b7-0d2a6671e7cd">

**Comment by CorradoLanera** [comment]
@jmcphers the issue still there to me.
![image](https://github.com/user-attachments/assets/31dfb78b-9d1c-433b-9fff-6a8bb33cc342)

Positron Version: 2024.07.0 (system setup) build 2024.07.0-100
Code - OSS Version: 1.91.0
Commit: 9d858046178da1bae0c31309db1a8d8f5ebc8b28
Date: 2024-07-26T03:19:27.206Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.26120

**Comment by testlabauto** [comment]
This does appear to be working now on OS X.  @jmcphers are there any logs that @CorradoLanera could provide to help understand what is happening on Windows?

**Comment by rmflight** [comment]
As of build 107, works for me on Linux.

**Comment by juliasilge** [comment]
On Windows with build 107, this works as well:

![image](https://github.com/user-attachments/assets/20e71a1f-3120-49b7-9fbc-54b9fef69f41)

I think this is ready to be called done @testlabauto. ✅

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-107
    OS Version          : OSX

### Test scenario(s) 

Verified on OSX, Linux and windows

Link(s) to TestRail test cases run or created: 
N/A

**Comment by CorradoLanera** [comment]
I confirm that w/ 107 works with me as well!!
![image](https://github.com/user-attachments/assets/3df79467-03ae-48a1-bfa2-6b2e402784be)
