### ISSUE TITLE
Newest plotly (6.0.0) doesn't work in Positron

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#6154]
#### Positron and OS details:

Main on 1/29/25
Ubuntu 24

#### Interpreter details:

Python 3.10.12

## Describe the issue:

New release of plotly:
https://github.com/plotly/plotly.py/releases

No longer works with:
https://github.com/posit-dev/qa-example-content/blob/main/workspaces/large_py_notebook/spotify.ipynb

## Steps to reproduce the issue:

1. Update to newest plotly
2. Run spotify.ipynb
3. Look for console errors (see below)

## Expected or desired behavior:
Plots generate

## Were there any error messages in the UI, Output panel, or Developer Tools console?

```
Plotly is not defined
ReferenceError: Plotly is not defined
    at <anonymous>:1:179
    at nt (https://file+.vscode-resource.vscode-cdn.net/home/runner/work/positron/positron/extensions/notebook-renderers/renderer-out/index.js:11:977)
    at Dt (https://file+.vscode-resource.vscode-cdn.net/home/runner/work/positron/positron/extensions/notebook-renderers/renderer-out/index.js:11:1686)
    at async Object.renderOutputItem (https://file+.vscode-resource.vscode-cdn.net/home/runner/work/positron/positron/extensions/notebook-renderers/renderer-out/index.js:121:185)
    at async Renderer.renderOutputItem (notebookWebviewPreloads.js:1504:17)
    at async Object._doRender (notebookWebviewPreloads.js:1788:17)
    at async Object.render (notebookWebviewPreloads.js:1761:19)
    at async OutputElement.render (notebookWebviewPreloads.js:2365:21)
    at async OutputCell.renderOutputElement (notebookWebviewPreloads.js:2209:13)
```

```
kP.select is not a function
TypeError: kP.select is not a function
    at Ehe (https://cdn.plot.ly/plotly-3.0.0.min.js:21:259206)
    at Object.Yft [as _doPlot] (https://cdn.plot.ly/plotly-3.0.0.min.js:21:255283)
    at Object.Qft [as newPlot] (https://cdn.plot.ly/plotly-3.0.0.min.js:21:260707)
    at <anonymous>:1:186
    at nt (https://file+.vscode-resource.vscode-cdn.net/home/runner/work/positron/positron/extensions/notebook-renderers/renderer-out/index.js:11:977)
    at Dt (https://file+.vscode-resource.vscode-cdn.net/home/runner/work/positron/positron/extensions/notebook-renderers/renderer-out/index.js:11:1686)
    at async Object.renderOutputItem (https://file+.vscode-resource.vscode-cdn.net/home/runner/work/positron/positron/extensions/notebook-renderers/renderer-out/index.js:121:185)
    at async Renderer.renderOutputItem (notebookWebviewPreloads.js:1504:17)
    at async Object._doRender (notebookWebviewPreloads.js:1788:17)
    at async Object.render (notebookWebviewPreloads.js:1761:19)
```

**Comment by testlabauto** [comment]
QA note:  unpin plotly when fixed:
https://github.com/posit-dev/qa-example-content/blob/main/requirements.txt

**Comment by arnaudh** [comment]
This seems to be a broader plotly 6.0.0 issue (not just in Positron): https://github.com/plotly/plotly.py/issues/5012

**Comment by juliasilge** [comment]
Apparently plotly 6.0 has a migration guide:
https://plotly.com/python/v6-migration/

**Comment by isabelizimm** [comment]
Could this be related to #6033 at all? I know that is for a different version of `plotly`, but both of these popping up at the same time seems suspicious 🤔

**Comment by nstrayer** [comment]
This was fixed in plotly 6.0.1. It works on my side of things. Can you recheck @testlabauto?

**Comment by testlabauto** [comment]
Looks good.  I can't test in CI at the moment, but locally it does seem to be resolved.

**Comment by testlabauto** [comment]
It does still fail in CI, though.  Its hard to understand what is happening, but I think its because three plots are generated for:

```
import hvplot.pandas
import pandas as pd
hvplot.extension('plotly')
pd.DataFrame(dict(x=[1,2,3], y=[4,5,6])).hvplot.scatter(x="x", y="y")
```

<img width="1030" alt="Image" src="https://github.com/user-attachments/assets/cced796b-28bc-4d73-9400-f6e999b435d8" />

Locally when I run the:
Python - Verify hvplot can load with plotly extension [C766660]
test, it passes, but it looks like the valid plot is first:

<img width="1531" alt="Image" src="https://github.com/user-attachments/assets/4251ba83-f254-416a-9515-760e3526bfee" />

In CI, it seems like the valid plot is not first.  Can we get to the bottom of why this creates three plots (two invalid and one valid)?

**Comment by testlabauto** [comment]
Seems like this is possibly related to: https://github.com/posit-dev/positron/issues/5991

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.05.0-125
    OS Version          : OSX

### Test scenario(s) 

Works according to the initial description.  Seeing another plotly bug but will file separately.

Link(s) to TestRail test cases run or created:
