### ISSUE TITLE
Common UX inconsistencies/imperfections

### ISSUE THREAD

**Issue by daattali** [posit-dev/positron#8935]
I noticed a few places that have the same UX issues (at least to me they are considered issues, maybe they're on purpose):
(1) Buttons that don't have tooltips
(2) Buttons that don't have a clearly differentiated hover state
(3) Areas that are not clickable but they have a "pointer" cursor that make them look clickable

Here are the places I noticed, but I'm sure there are lots more:

- In a data viewer editor, the two buttons for filters don't have tooltips to explain what they do and they don't have hover states <img width="70" height="34" alt="Image" src="https://github.com/user-attachments/assets/75ac5e7c-7007-459c-b2d6-031e5d87bd88" />  

- After creating a filter, the filter that appears doesn't have a tooltip (something like "Edit this filter") <img width="111" height="33" alt="Image" src="https://github.com/user-attachments/assets/81522246-4acf-4afb-a4c0-ffb60f8af6c8" />

- The "X" button inside that filter also doesn't have a tooltip. Additionally, the hover state on the X is very faint, and it's not clear that clicking the X will perform a different action than clicking the rest of the filter. The hover state on the X should be more clearly differentiated.

- The "clear column sorting" button above them appears clickable always because it has a hover state, even when it's disabled 

<img width="254" height="67" alt="Image" src="https://github.com/user-attachments/assets/8ca21a0f-36ee-47b2-b780-3c2aa02a1621" />

- The entire row beside the "clear column sorting" button appears clickable because of a pointer cursor, but nothing happens when you click anywhere on that row

- In the table section of the data viewer editor, the top left cell of the table (above the row names, left of the column names) has a pointer cursor which makes me think that if I click that cell something will get selected, but nothing happens<img width="332" height="149" alt="Image" src="https://github.com/user-attachments/assets/24a39dd6-3bc5-4d53-9957-bfc11e78f85f" />

- In the Session panel, the VARIABLES row is clickable along the entire row, and clicking anywhre causes a collapse/expansion of that section. This is fine. But within that VARIABLES section, the SMALL/MEDIUM/LARGE headers also have a hover state but nothing happens if you click on their rows. They only collapse/expand if you click on the chevron arrow, but not if you click anywhere else. 

https://github.com/user-attachments/assets/7e93d4af-e103-4d31-85c3-52530c01e8eb

**Comment by juliasilge** [comment]
Let's look at the polish items for the Data Explorer in 2025.10, and open followup issues for anything we don't get.

**Comment by dhruvisompura** [comment]
> - In a data viewer editor, the two buttons for filters don't have tooltips to explain what they do and they don't have hover states <img width="70" height="34" alt="Image" src="https://github.com/user-attachments/assets/75ac5e7c-7007-459c-b2d6-031e5d87bd88" />  
> 
> - After creating a filter, the filter that appears doesn't have a tooltip (something like "Edit this filter") <img width="111" height="33" alt="Image" src="https://github.com/user-attachments/assets/81522246-4acf-4afb-a4c0-ffb60f8af6c8" />
> 
> - The "X" button inside that filter also doesn't have a tooltip. Additionally, the hover state on the X is very faint, and it's not clear that clicking the X will perform a different action than clicking the rest of the filter. The hover state on the X should be more clearly differentiated.
> 
> - The "clear column sorting" button above them appears clickable always because it has a hover state, even when it's disabled <img width="254" height="67" alt="Image" src="https://github.com/user-attachments/assets/8ca21a0f-36ee-47b2-b780-3c2aa02a1621" />

^ The following issues in the data explorer are being addressed in [9521](https://github.com/posit-dev/positron/pull/9521)

--

> - The entire row beside the "clear column sorting" button appears clickable because of a pointer cursor, but nothing happens when you click anywhere on that row

I did some poking around and I think this CSS issue is also a problem in upstream because the same issue is present in the editor tab action bar as well. The positron action bar used by the data explorer is built on top of the base action bar so its inheriting this issue.

--

> - In the table section of the data viewer editor, the top left cell of the table (above the row names, left of the column names) has a pointer cursor which makes me think that if I click that cell something will get selected, but nothing happens<img width="332" height="149" alt="Image" src="https://github.com/user-attachments/assets/24a39dd6-3bc5-4d53-9957-bfc11e78f85f" />

This isn't a bug! The empty top left cell is clickable and navigates users back to the beginning of the dataset when they are scrolled in the middle of the dataset. We also have a tooltip explaining what happens when clicked. I wonder if the delay on the tooltips is the real issue? Looks like that is being discussed in #9121. I don't think this needs to be addressed as part of this issue.

Here's a video of what clicking this cell does:

https://github.com/user-attachments/assets/877ee1e8-6989-45d6-8bcb-66276b00ce7e

--

> - In the Session panel, the VARIABLES row is clickable along the entire row, and clicking anywhre causes a collapse/expansion of that section. This is fine. But within that VARIABLES section, the SMALL/MEDIUM/LARGE headers also have a hover state but nothing happens if you click on their rows. They only collapse/expand if you click on the chevron arrow, but not if you click anywhere else. 
> 
> https://github.com/user-attachments/assets/7e93d4af-e103-4d31-85c3-52530c01e8eb

Opening up a new issue for this and sending to triage as its not part of the data explorer work: https://github.com/posit-dev/positron/issues/9522

**Comment by rodrigosf672** [comment]
@dhruvisompura or @juliasilge: These three clickable icons still don't have tooltips. Should I open a new issue for them? 

1) Slider to between columns list and table
<img width="38" height="547" alt="Image" src="https://github.com/user-attachments/assets/fa5480bd-1852-4629-ac4b-4a06d490d393" />

2) Expandable arrows on the left of column names in columns' list
<img width="35" height="500" alt="Image" src="https://github.com/user-attachments/assets/edda1e2e-00d0-4db8-a3f6-5cf45e8008cb" />

3) Elipsis menu on column headers
<img width="34" height="34" alt="Image" src="https://github.com/user-attachments/assets/9e9a45e7-b007-407d-9796-cbe5ca862c4d" />

**Comment by rodrigosf672** [comment]
### Verified Fixed
    Positron Version(s) : 2025.10.0 build 131
    OS Version          : macOS Sequoia 15.6.1

### Test scenario(s) 
- Tooltips verification
- Differentiation of hover states (when applicable)
- Clickable vs. non-clickable states
